### PR TITLE
Slow controller

### PR DESCRIPTION
**Pull request by oni303**
My daily PR:

This is a 10Hz version of the PID controller.
Is is less noisy but there are still some clicks noticeable.

### CODE REVIEW

**Comment by yschroeder** [comment]
Ok, we should test this PR and merge if it works.

But we should still address the problem of the noisy tip. Depending on how noisy it is now (have to hear it by myself to judge) we could either go with it as being ok for a cheap soldering station or tackle it until the tip is quiet.

**Comment by oni303** [comment]
# "Great neeews everyone:"
Today I did the first solder joints the our soldering station.
**WORKS, like a charm**
And I did not hear noises form the tip. Well I did not place mu ear to near to the hot tip.

**Comment by yschroeder** [comment]
Good job :+1: 

Maybe the problem with the noise gets worse when the heating cycles are very short so you have two sharp edges on the power close together. If the heating works with realistic pulse widths it may not be audible.

**Comment by yschroeder** [comment]
I have seen it working, let's merge it

**Pull request merged**
