### PR TITLE
Added a eeprom config loader

### PR DESCRIPTION
**Pull request by oni303**
this enables the settings to survive software updates

WARNING: I was not able to test this due to the lack of a board. Test before merging!!!
Please test it by running "TARGET=tests/config_test make" then see what happens, then cycle the power and see if no "ERR" is shown anymore.

### CODE REVIEW

**Comment by kartenkarsten** [comment]
I had to merge master to this branch to get the right include path
after running "TARGET=tests/config_test make" it compiles the test program but doesn't flash it.
"TARGET=tests/config_test make program" doesn't work - and stops with this error
"make: *** Keine Regel vorhanden, um das Ziel „program-tests/config_test“, benötigt von „program“, zu erstellen.  Schluss."
any idea?

**Comment by oni303** [comment]
sorry, just fixed it in #11

**Comment by kartenkarsten** [comment]
there is still sth wired.
eeprom file is empty  ```avrdude: writing eeprom (0 bytes):```
and I get a floating point exception
```Makefile:194: die Regel für Ziel „program-eeprom-config_test“ scheiterte
make: *** [program-eeprom-config_test] Gleitkomma-Ausnahme (Speicherauszug erstellt)```

**Comment by oni303** [comment]
ok I just got hardware so I will try it now my self

**Comment by oni303** [comment]
Ok it works now.
But I have never seen your exception.

**Comment by kartenkarsten** [comment]
it's gone for me as well ```TARGET=tests/config_test make``` works fine and programming as well.
But if I use ```TARGET=tests/config_test make programm``` (with out already created hex file) no Rule to create TARGET program-config_test could be found.

**Comment by oni303** [comment]
Well I see, there are some things to be fixed in the make file.
I will do that as soon as possible

**Comment by oni303** [comment]
Just did some more Makefile hacking.
Fixed it

**Comment by kartenkarsten** [comment]
thanks

**Pull request merged**
