### PR TITLE
Added third and fourth action to buttons

### PR DESCRIPTION
**Pull request by oni303**
third action is triggered by pushing both buttons for <2s

fourth action is triggered by pushing both buttons for >2s

### CODE REVIEW

**Comment by yschroeder** [comment]
There is a bug in this PR: When I hit both buttons shortly one after the other then the third action is triggered. Example: I want to increase the temperature but I miss the target temp by pressing the button for too long. When I immediately press the minus button it triggers the third action although the plus button is not pressed any more.

**Comment by oni303** [comment]
@dreimers can you test if the bug is fixed?

**Comment by yschroeder** [comment]
@dreimers tested it: instead of triggering the third action it does nothing now. I think it would be better if it triggered the correct action for pressing only one button instead.

**Comment by dreimers** [comment]
Tested and it works fine :+1:

**Pull request merged**
